version: "3.8"
   
services:
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
  api:
    restart: always
    image: your_docker_image_name
    depends_on:
      - db
    container_name: your_container_name
    env_file: .env 
    ports:
        - "8000:8000"
    command: bash -c "
         python manage.py makemigrations && 
         python manage.py migrate && 
         python manage.py runserver 0.0.0.0:8000" 
    
    


